### ISSUE TITLE
Make it compatibile with both py2 and py3

### ISSUE THREAD

**Issue by rimek** [rimek/fatek-fbs-lib#6]

**Comment by sih4sing5hong5** [comment]
Is `pymodbus3` compatible with `python2` ?
I tried `pymodbus` but it only worked in python2

**Comment by netrounds-rimek** [comment]
`pymodbus3` is only for python3. But I want to make this lib  work both in python versions so it has to detect if `pymodbus3` is available and use `pymodbus` if not

**Comment by sih4sing5hong5** [comment]
https://travis-ci.org/i3thuan5/fatek-fbs-lib/builds/204122904
It seems `pymodbus` is not compatible with python3 and `pymodbus3` is not compatible with python2.
If it must be compatible with them, `pymodbus*` should be removed from `setup.py` and `requirements.txt`.
